#!/usr/bin/env python3
"""Generate station ID stabs with musical stings for Dead Internet Radio.

Each station ID gets:
1. A musical sting generated by ACE-Step (5-15s synth/bass/pad)
2. A TTS voiceover via Kokoro
3. Mixed together with ffmpeg

Run requires ACE-Step running at localhost:8001.
"""
import os
import sys
import subprocess
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "")
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
ACE_STEP_URL = os.getenv("ACE_STEP_URL", "http://localhost:8001")

VOICES = [
    "bm_daniel",
    "bm_fable",
    "bm_george",
    "bm_lewis",
]

KOKORO_PYTHON = Path(__file__).parent / "kokoro" / ".venv" / "bin" / "python3"
ANNOUNCE_SCRIPT = Path(__file__).parent / "announce.py"

FALLBACK_IDS = [
    "You're locked into D.I.R.",
    "Dead Internet on your dial.",
    "This is the frequency.",
    "DIR. The only station left.",
    "The signal finds you.",
    "Transmission confirmed.",
    "Still here. Still transmitting.",
    "If you can hear this, you're still connected.",
    "The world ended. The radio didn't.",
    "DIR is live.",
]

FALLBACK_JINGLES = [
    "Dead. Internet. Radio.",
    "D. I. R.",
    "The last frequency.",
    "Still transmitting.",
    "One frequency. One signal.",
    "Locked on. Transmitted. Received.",
]


# ---------------------------------------------------------------------------
# LLM
# ---------------------------------------------------------------------------

def call_llm(system_prompt, user_message, json_mode=False):
    import json
    import time
    import urllib.request
    import urllib.error

    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
    }
    body = {
        "model": OPENROUTER_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        "temperature": 0.9,
    }
    if json_mode:
        body["response_format"] = {"type": "json_object"}
    for attempt in range(3):
        try:
            req = urllib.request.Request(
                OPENROUTER_URL,
                data=json.dumps(body).encode(),
                headers=headers,
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=120) as resp:
                result = json.loads(resp.read().decode())
                content = result["choices"][0]["message"]["content"]
                if content is None:
                    raise ValueError("LLM returned null content")
                return content
        except urllib.error.HTTPError as e:
            if e.code == 429:
                wait = 3 * (attempt + 1)
                print(f"  Rate limited, retrying in {wait}s...", flush=True)
                time.sleep(wait)
                continue
            print(f"  LLM call failed ({e.code})", flush=True)
            break
        except Exception as e:
            print(f"  {e}", flush=True)
            break
    return None


def generate_texts(prompt_path, count):
    """Generate station IDs and jingles via LLM."""
    if not OPENROUTER_API_KEY:
        print("  No OPENROUTER_API_KEY, using fallback texts", flush=True)
        return FALLBACK_IDS, FALLBACK_JINGLES

    prompt = Path(prompt_path).read_text().strip()
    print("  Generating texts via LLM...", flush=True)
    user_msg = (
        f"Generate station IDs and jingles for Dead Internet Radio.\n"
        f"I need {count} total items (mix of IDs and jingles). "
        f"Produce enough variety to fill that count."
    )
    raw = call_llm(prompt, user_msg, json_mode=True)
    if raw is None:
        print("  LLM failed, using fallback texts", flush=True)
        return FALLBACK_IDS, FALLBACK_JINGLES

    try:
        data = json.loads(raw)
        ids = data.get("ids", [])
        jingles = data.get("jingles", [])
        if len(ids) < 3 or len(jingles) < 2:
            raise ValueError("Too few items")
        print(f"  Got {len(ids)} IDs, {len(jingles)} jingles", flush=True)
        return ids, jingles
    except Exception as e:
        print(f"  LLM parse failed ({e}), using fallback texts", flush=True)
        return FALLBACK_IDS, FALLBACK_JINGLES


def generate_sting_caption():
    """Use LLM to generate a musical sting description for ACE-Step."""
    if not OPENROUTER_API_KEY:
        return _fallback_sting_caption()

    system = (
        "You generate short musical sting descriptions for a dark, mechanical "
        "radio station. Output a JSON object with a 'caption' field containing "
        "a technical sound design description (no poetry, no metaphors). "
        "2-3 sentences. Name synths, frequencies, drum sounds, effects."
    )
    user = (
        "Generate a short musical sting (5-15 seconds) for a radio station ID. "
        "Think: synth stab, bass drop, pad swell, filter sweep, or dark drone. "
        "Technical description only — concrete synth types, frequency ranges, "
        "drum sounds, effects. Output JSON: {\"caption\": \"...\"}"
    )
    raw = call_llm(system, user, json_mode=True)
    if raw is None:
        return _fallback_sting_caption()
    try:
        data = json.loads(raw)
        return data.get("caption", "") or _fallback_sting_caption()
    except Exception:
        return _fallback_sting_caption()


FALLBACK_STING_CAPTIONS = [
    "Dark analog synth stab at 80Hz with long reverb tail, falling filter sweep from 2kHz to 200Hz, subtle tape hiss.",
    "Deep sub-bass drop from 100Hz to 30Hz, metallic percussion hit, cathedral reverb, slow decay.",
    "FM synthesis bell tone at 1200Hz with ring modulation, granular delay, fading into static.",
    "Sawtooth synth chord stab at 120 BPM in D minor, sidechain compression, dark pad wash underneath.",
    "Single bass drum hit at 60Hz with analog saturation, long reverb tail 4 seconds, noise floor fade in.",
    "Filtered white noise sweep from 8kHz down to 200Hz, pulse-width modulated square wave underneath, tight room reverb.",
    "Plucked synth arpeggio C minor, 16th notes at 100 BPM, tape delay feedback, lo-fi bitcrushed tail.",
    "Low drone at 55Hz with slow LFO amplitude modulation, metallic resonance at 3.5kHz, industrial reverb.",
]


def _fallback_sting_caption():
    return random.choice(FALLBACK_STING_CAPTIONS)


# ---------------------------------------------------------------------------
# ACE-Step
# ---------------------------------------------------------------------------

def check_ace_step():
    import urllib.request
    try:
        req = urllib.request.Request(f"{ACE_STEP_URL}/health")
        with urllib.request.urlopen(req, timeout=5) as resp:
            data = __import__("json").loads(resp.read().decode())
            return data.get("data", {}).get("status") == "ok"
    except Exception:
        return False


def generate_sting(caption, key=None, bpm=None):
    """Generate a short musical sting via ACE-Step. Returns path to wav file."""
    import json
    import time
    import urllib.request

    body = {
        "prompt": caption,
        "lyrics": "",
        "bpm": bpm,
        "key_scale": key or "",
        "audio_duration": random.randint(5, 12),
        "thinking": True,
        "audio_format": "mp3",
    }
    req = urllib.request.Request(
        f"{ACE_STEP_URL}/release_task",
        data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read().decode())
            task_id = data["data"]["task_id"]
    except Exception as e:
        print(f"  ACE-Step submission failed: {e}", file=sys.stderr)
        return None

    # Poll
    start = time.time()
    while time.time() - start < 300:
        body = {"task_id_list": [task_id]}
        req = urllib.request.Request(
            f"{ACE_STEP_URL}/query_result",
            data=json.dumps(body).encode(),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = json.loads(resp.read().decode())
        except Exception:
            time.sleep(5)
            continue
        task = data["data"][0]
        if task["status"] == 1:
            result = json.loads(task["result"])
            audio_url = result[0]["file"]
            out_path = Path(f"station-ids/.tmp-sting-{task_id[:8]}.mp3")
            urllib.request.urlretrieve(f"{ACE_STEP_URL}{audio_url}", out_path)
            return out_path
        elif task["status"] == 2:
            print(f"  ACE-Step task failed", file=sys.stderr)
            return None
        elapsed = int(time.time() - start)
        print(f"  Generating sting... ({elapsed}s)", flush=True)
        time.sleep(5)

    print("  ACE-Step timed out", file=sys.stderr)
    return None


# ---------------------------------------------------------------------------
# TTS
# ---------------------------------------------------------------------------

def generate_tts(text, voice, output_path, intensity=0.3):
    """Generate TTS via announce.py."""
    cmd = [
        str(KOKORO_PYTHON),
        str(ANNOUNCE_SCRIPT),
        "--text", text[:300],
        "--output", str(output_path),
        "--voice", voice,
        "--intensity", str(intensity),
    ]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True, timeout=300)
        return output_path.exists() and output_path.stat().st_size > 100
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        return False


# ---------------------------------------------------------------------------
# Mix
# ---------------------------------------------------------------------------

def mix_sting_and_voice(sting_path, voice_path, out_path):
    """Mix musical sting with TTS voiceover using ffmpeg.
    Voiceover starts 0.5s in, sting ducks under voice, fades out at end."""
    try:
        cmd = [
            "ffmpeg", "-y",
            "-i", str(sting_path),
            "-i", str(voice_path),
            "-filter_complex",
            # Voice delayed 0.5s, sting ducks: volume drops when voice is present
            "[0:a]volume=0.6[sting];"
            "[1:a]adelay=500|500,volume=1.2[voice];"
            "[sting][voice]amix=inputs=2:duration=longest:dropout_transition=2,"
            "afade=t=out:st=8:d=2,"
            "loudnorm=I=-16:TP=-1.5:LRA=11[out]",
            "-map", "[out]",
            "-ar", "24000",
            str(out_path),
        ]
        subprocess.run(cmd, check=True, capture_output=True, timeout=30)
        return out_path.exists()
    except Exception as e:
        print(f"  ffmpeg mix failed: {e}", file=sys.stderr)
        return False


def mix_sting_only(sting_path, out_path):
    """Just apply effects to the sting, no voiceover."""
    try:
        cmd = [
            "ffmpeg", "-y",
            "-i", str(sting_path),
            "-af",
            "volume=0.7,afade=t=out:st=8:d=2,loudnorm=I=-16:TP=-1.5:LRA=11",
            "-ar", "24000",
            str(out_path),
        ]
        subprocess.run(cmd, check=True, capture_output=True, timeout=30)
        return out_path.exists()
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

import random

def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate station IDs with musical stings")
    parser.add_argument("--output", "-o", type=Path, default=Path("station-ids"))
    parser.add_argument("--count", "-n", type=int, default=10,
                        help="Total IDs to generate (default: 10)")
    parser.add_argument("--no-stings", action="store_true",
                        help="Skip ACE-Step stings, TTS only")
    parser.add_argument("--no-llm", action="store_true",
                        help="Skip LLM, use fallback texts")
    parser.add_argument("--prompt", type=Path,
                        default=Path(__file__).parent / "prompts" / "station_ids.md")
    args = parser.parse_args()

    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / ".tmp").mkdir(exist_ok=True)
    print(f"Output: {args.output}/")

    # Check ACE-Step
    ace_ok = False
    if not args.no_stings:
        ace_ok = check_ace_step()
        if not ace_ok:
            print("  WARNING: ACE-Step not reachable — stings will be skipped", flush=True)
            print(f"  Start it: cd ACE-Step-1.5 && uv run acestep-api", flush=True)
        else:
            print("  ACE-Step: OK", flush=True)

    # Generate texts
    print("Preparing texts...", flush=True)
    if args.no_llm:
        ids, jingles = FALLBACK_IDS, FALLBACK_JINGLES
    else:
        ids, jingles = generate_texts(args.prompt, args.count)

    pool = [(t, "id") for t in ids] + [(t, "jingle") for t in jingles]
    random.shuffle(pool)
    pool = pool[:args.count]

    total = 0
    failed = 0

    for text, kind in pool:
        slug = "".join(c if c.isalnum() else "-" for c in text.lower()).strip("-")[:30]
        out_path = args.output / f"{kind}-{slug}.wav"

        if out_path.exists():
            continue

        voice = random.choice(VOICES)
        print(f"  [{kind}] \"{text[:50]}\"")

        # 1. Generate musical sting
        sting_path = None
        if ace_ok:
            print(f"    Generating sting...", end="", flush=True)
            caption = generate_sting_caption()
            if caption:
                print(f" ({caption[:40]}...)", flush=True)
                sting_path = generate_sting(caption)
            else:
                print(" (caption failed)", flush=True)

        # 2. Generate TTS
        voice_path = args.output / ".tmp" / f"voice-{slug}.wav"
        print(f"    TTS [{voice}]...", end="", flush=True)
        tts_ok = generate_tts(text, voice, voice_path)
        if not tts_ok:
            print(" FAILED")
            failed += 1
            continue
        print(" OK")

        # 3. Mix or TTS-only
        if sting_path:
            print(f"    Mixing...", end="", flush=True)
            if mix_sting_and_voice(sting_path, voice_path, out_path):
                print(f" → {out_path.name}")
                total += 1
            else:
                # Fallback: just use the TTS
                voice_path.rename(out_path)
                print(f" (mix failed, voice only) → {out_path.name}")
                total += 1
            sting_path.unlink(missing_ok=True)
        else:
            voice_path.rename(out_path)
            print(f"    → {out_path.name} (voice only)")
            total += 1

    # Cleanup
    tmp_dir = args.output / ".tmp"
    if tmp_dir.exists():
        for f in tmp_dir.iterdir():
            f.unlink()
        tmp_dir.rmdir()

    print(f"\nDone: {total} generated, {failed} failed, {args.output}/")


if __name__ == "__main__":
    main()
